changed wifi checker for rockpi

diff --git a/run/archiveloop b/run/archiveloop
--- a/run/archiveloop
+++ b/run/archiveloop
@@ -709,6 +709,36 @@ function logrotator {
   done
 }
 
+# function wifichecker {
+#   dmesg -w | {
+#     while TMOUT=1 read -r line; do
+#       true
+#     done
+#     wifi=working
+#     while read -r line; do
+#       case $line in
+#       *"failed to enable fw supplicant")
+#         if [ "$wifi" = "working" ]; then
+#           wifi="notworking"
+#         else
+#           log "restarting wifi because of: $line"
+#           modprobe -r brcmfmac cfg80211 brcmutil || true
+#           modprobe brcmfmac || true
+#           while TMOUT=1 read -r line; do
+#             true
+#           done
+#           wifi="working"
+#         fi
+#         ;;
+#       *)
+#         wifi=working
+#         ;;
+#       esac
+#     done
+#   }
+# }
+
+#rockpi
 function wifichecker {
   dmesg -w | {
     while TMOUT=1 read -r line; do
@@ -717,12 +747,12 @@ function wifichecker {
     wifi=working
     while read -r line; do
       case $line in
-      *"failed to enable fw supplicant")
+      *"brcmf_cfg80211_scan: scan error (-110)"* | *"brcmf_proto_bcdc_msg failed w/status -110"*)
         if [ "$wifi" = "working" ]; then
           wifi="notworking"
         else
           log "restarting wifi because of: $line"
-          modprobe -r brcmfmac cfg80211 brcmutil || true
+          modprobe -r brcmfmac_wcc brcmfmac cfg80211 brcmutil || true
           modprobe brcmfmac || true
           while TMOUT=1 read -r line; do
             true
